name: Publish Relay VS Code Extension
on:
  workflow_dispatch:

jobs:
  vscode-release:
    name: VSCode Extension Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vscode-extension
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: ESLint
        run: yarn --ignore-engines run lint
      - name: Prettier
        run: yarn --ignore-engines run prettier-check
      - name: Typecheck
        run: yarn --ignore-engines run typecheck
      - name: Publish
        run: yarn --ignore-engines vsce publish --pat ${{ secrets.VSCE_PAT }}
